### ISSUE TITLE
Compliments

### ISSUE THREAD

**Issue by edoss00** [kazijamal/TwoFortyNine_jamalK-lauE-leeR#2]
- I like the idea of using the word clouds to measure sentiment
- The organization of the pages of you app seem well thought out
- Color coding the site map makes it clear and easy to read
- You guys included a lot of datasets that were off the beaten path
- Your component map is clear and well-done

by MarshmallowFlush

**Comment by kazijamal** [comment]
Thank you for the constructive feedback!

-- Team TwoFortyNine :: Kazi Jamal, Eric Lau, and Raymond Lee
