### ISSUE TITLE
The SIMPsons review

### ISSUE THREAD

**Issue by DavidLupea** [kazijamal/TwoFortyNine_jamalK-lauE-leeR#4]
- Explain how you will get and analyze the numbers section of your website.
- This isn't really an issue but you should consider using one data format so all the info is in the same format and it is easier to expand. 
- The data transfer system is very thorough.
- We like how you have potential additional features.
- We like how you used external packages and describe what they do.

**Comment by kazijamal** [comment]
Thank you for the constructive feedback!

-- Team TwoFortyNine :: Kazi Jamal, Eric Lau, and Raymond Lee
